# Generated by Django 4.2 on 2023-05-29 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BilderFestlegen',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='name')),
                ('area', models.CharField(choices=[('HP', 'Startseiten-Bilder'), ('AM', 'Übermich-Bilder'), ('G', 'Galerie-Bilder')], max_length=20, verbose_name='area')),
                ('image', models.ImageField(upload_to='images/', verbose_name='image')),
                ('width', models.IntegerField(blank=True, null=True, verbose_name='width')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='height')),
            ],
            options={
                'verbose_name': 'Bild',
                'verbose_name_plural': 'Bilder',
            },
        ),
        migrations.CreateModel(
            name='Farben',
            fields=[
                ('area', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='area')),
                ('farbcode', models.CharField(max_length=20, verbose_name='farbcode')),
            ],
            options={
                'verbose_name': 'Farbe',
                'verbose_name_plural': 'Farben',
            },
        ),
    ]
