# Generated by Django 4.2 on 2023-05-10 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bilder',
            fields=[
                ('area', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='area')),
                ('image', models.ImageField(upload_to='images/', verbose_name='image')),
                ('height', models.IntegerField(verbose_name='height')),
            ],
            options={
                'verbose_name': 'Bild',
                'verbose_name_plural': 'Bilder',
            },
        ),
    ]
