# Generated by Django 4.2 on 2023-05-29 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_texte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='texte',
            name='text',
            field=models.TextField(max_length=1000, verbose_name='text'),
        ),
    ]
