# Generated by Django 4.2 on 2023-05-20 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_bilder_width'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farben',
            fields=[
                ('area', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='area')),
                ('farbcode', models.CharField(max_length=20, verbose_name='farbcode')),
            ],
            options={
                'verbose_name': 'Farbe',
                'verbose_name_plural': 'Farben',
            },
        ),
    ]
