# Generated by Django 4.2 on 2023-05-29 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_texte_text'),
    ]

