# Generated by Django 4.2 on 2023-05-26 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_farben'),
    ]

    operations = [
        migrations.CreateModel(
            name='BilderFestlegen',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='name')),
                ('area', models.CharField(max_length=20, verbose_name='area')),
                ('image', models.ImageField(upload_to='images/', verbose_name='image')),
                ('height', models.IntegerField(verbose_name='height')),
                ('width', models.IntegerField(null=True, verbose_name='width')),
            ],
            options={
                'verbose_name': 'Bild',
                'verbose_name_plural': 'Bilder',
            },
        ),
        migrations.DeleteModel(
            name='Bilder',
        ),
    ]
