# Generated by Django 4.2 on 2023-05-25 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_farben'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galerie',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='area')),
                ('image', models.ImageField(upload_to='images/galerie')),
            ],
            options={
                'verbose_name': 'Galerie',
                'verbose_name_plural': 'Galerie-Bilder',
            },
        ),
        migrations.AlterField(
            model_name='bilder',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='Bild'),
        ),
    ]
