# Generated by Django 4.2 on 2023-05-31 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_galerie_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bilderfestlegen',
            name='area',
            field=models.CharField(choices=[('HP', 'Startseiten-Bilder'), ('AM', 'Übermich-Bilder'), ('Galerie-Bilder', 'Galerie-Bilder')], max_length=20, verbose_name='area'),
        ),
        migrations.AlterField(
            model_name='texte',
            name='text',
            field=models.TextField(max_length=2000, verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='texte',
            name='textfeld',
            field=models.CharField(max_length=25, primary_key=True, serialize=False, verbose_name='text-Feld'),
        ),
    ]
