# Generated by Django 4.2 on 2023-05-25 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_galerie_alter_bilder_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='galerie',
            name='breite',
            field=models.IntegerField(default=1, verbose_name='Breite'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='galerie',
            name='höhe',
            field=models.IntegerField(default=1, verbose_name='Höhe'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bilder',
            name='area',
            field=models.CharField(choices=[('galerie', 'GALERIE-BILD'), ('startseiten', 'WEBSEITEN-BILD'), ('über-mich', 'ÜBER-MICH-BILD')], default='galerie', max_length=14, primary_key=True, serialize=False, verbose_name='area'),
        ),
        migrations.AlterField(
            model_name='bilder',
            name='width',
            field=models.IntegerField(default=1, verbose_name='width'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='galerie',
            name='image',
            field=models.ImageField(upload_to='images/galerie', verbose_name='Bild'),
        ),
        migrations.AlterField(
            model_name='galerie',
            name='name',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Bildname'),
        ),
    ]
