# Generated by Django 4.2 on 2023-05-27 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_bilderfestlegen_delete_bilder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bilderfestlegen',
            name='area',
            field=models.CharField(choices=[('HP', 'Startseiten-Bilder'), ('AM', 'Übermich-Bilder'), ('G', 'Galerie-Bilder')], max_length=20, verbose_name='area'),
        ),
        migrations.AlterField(
            model_name='bilderfestlegen',
            name='height',
            field=models.IntegerField(blank=True, null=True, verbose_name='height'),
        ),
        migrations.AlterField(
            model_name='bilderfestlegen',
            name='width',
            field=models.IntegerField(blank=True, null=True, verbose_name='width'),
        ),
    ]
