# Generated by Django 4.2 on 2023-05-25 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_galerie_breite_galerie_höhe_alter_bilder_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bilder',
            name='id',
            field=models.IntegerField(auto_created=True, default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bilder',
            name='area',
            field=models.CharField(choices=[('galerie', 'GALERIE-BILD'), ('startseiten', 'STARTSEITEN-BILD'), ('über-mich', 'ÜBER-MICH-BILD')], default='galerie', max_length=14, verbose_name='Bereich'),
        ),
        migrations.AlterField(
            model_name='bilder',
            name='height',
            field=models.IntegerField(blank=True, null=True, verbose_name='height'),
        ),
        migrations.AlterField(
            model_name='bilder',
            name='width',
            field=models.IntegerField(blank=True, null=True, verbose_name='width'),
        ),
    ]
