# Generated by Django 4.2.1 on 2023-06-02 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_bilderfestlegen_area_alter_texte_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bilderfestlegen',
            name='area',
            field=models.CharField(choices=[('HP', 'Startseiten-Bilder'), ('AM', 'Übermich-Bilder'), ('Galerie-Bilder', 'Galerie-Bilder'), ('GE', 'Galerie-Wohnz-Hintergrund')], max_length=25, verbose_name='area'),
        ),
    ]
