# Generated by Django 4.2.1 on 2023-06-02 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_bilderfestlegen_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='bilderfestlegen',
            name='desc',
            field=models.IntegerField(blank=True, null=True, verbose_name='beschreibung'),
        ),
    ]
