# Generated by Django 4.2 on 2023-05-25 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_bilder_id_alter_bilder_area_alter_bilder_height_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bilder',
            name='id',
        ),
        migrations.AddField(
            model_name='bilder',
            name='name',
            field=models.CharField(default=1, max_length=20, primary_key=True, serialize=False, verbose_name='name'),
            preserve_default=False,
        ),
    ]
